[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rv16-lib"
version = "1.0.0"
description = "A shared Python utility library for the raVioleria16 project."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
"PyYAML",
"pydantic"
]